---
# Handle plugins
# Wait for pulling the Jenkins CLI, assuming 10s should be sufficiant
- name: 10s delay while installing plugins
  wait_for: port=8080 delay=10
  tags:
    - plugins
    - cli

# Get Jenkins CLI from localhost
- name: Get Jenkins CLI
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=${cli_dest} mode=0440
  tags:
    - cli

# Jenkins Update-center
- name: Update-center Jenkins
  shell: "curl  -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"
  tags:
    - plugins
    - cli

# Install/update Jenkins plugins
- name: Install/update plugins
  command: java -jar ${cli_dest} -s http://localhost:8080 install-plugin ${item}
  only_if: is_set('$plugins')
  with_items: $plugins
  tags:
    - plugins
    - cli

# Wait for Jenkins to install plugins, assuming 10s should be sufficiant
- name: 10s delay while installing plugins
  wait_for: port=8080 delay=10
  tags:
    - plugins
    - cli

# Safe-restart Jenkins
- name: Safe-restart Jenkins
  command: java -jar ${cli_dest} -s http://localhost:8080 safe-restart
  tags:
    - plugins
    - cli