---
# Install Jenkins repository

# Provides add-apt-repository
- name: Install python-software-properties
  apt: pkg=python-software-properties state=installed update-cache=yes
  tags:
    - jenkins-repo

# Add Jenkins repository key
- name: Add jenkins apt-key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present
  tags:
    - jenkins-repo

# Add Jenkins repository
- name: Add Jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  tags:
    - jenkins-repo

# Ugly workaround fixing the auto-add src repo when using apt_repository
- name: Remove invalid Jenkins src repository
  command: sed --in-place '/deb-src.*pkg.jenkins-ci/d' /etc/apt/sources.list
  tags:
    - jenkins-repo